import { describe, it, expect } from 'vitest';
import { mkdir, mkdtemp, rm, utimes, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { visibleWidth } from '@earendil-works/pi-tui';
import { agentCommand, analyzeGaudRouting, buildGaudDelegationPrompt, buildWorkerPlans, createAutogeneratedPlan, discoverDefaultPlanPath, extractPlanPath, findLatestActiveRun, formatWorkerApprovalSummary, gaudWidgetForUi, renderAskUserDialogLines, resolvePlanningSource, workerEnvPrefix } from '../extensions/gaud/index.js';
import type { GaudRunState } from '../extensions/gaud/index.js';

describe('State Serialization', () => {
  it('should serialize and deserialize a GaudRunState object correctly', () => {
    const run: GaudRunState = {
      id: 'gaud-123',
      status: 'running',
      task: 'implement feature',
      createdAt: Date.now(),
      updatedAt: Date.now(),
      repoRoot: '/root',
      runDir: '/root/.gaud/runs/gaud-123',
      eventsPath: '/root/.gaud/runs/gaud-123/events.jsonl',
      statePath: '/root/.gaud/runs/gaud-123/state.json',
      tmuxSocket: 'gaud-123',
      tmuxSession: 'gaud-123',
      workers: {},
      lastEventOffset: 0,
    };

    const json = JSON.stringify(run);
    const deserialized = JSON.parse(json) as GaudRunState;

    expect(deserialized.id).toBe(run.id);
    expect(deserialized.status).toBe(run.status);
    expect(deserialized.task).toBe(run.task);
  });
});

describe('Polling Bridge - Event Parsing', () => {
  it('should parse valid callback events from a JSONL string', () => {
    const eventsJsonl = [
      JSON.stringify({ ts: Date.now(), runId: 'gaud-123', workerId: 'frontend', type: 'done', summary: 'Implemented UI' }),
      JSON.stringify({ ts: Date.now(), runId: 'gaud-123', workerId: 'backend', type: 'waiting-user', question: 'Confirm API' }),
    ].join('\n');

    const lines = eventsJsonl.split('\n');
    const parsedEvents = lines.map(line => JSON.parse(line));

    expect(parsedEvents).toHaveLength(2);
    expect(parsedEvents[0].workerId).toBe('frontend');
    expect(parsedEvents[0].type).toBe('done');
    expect(parsedEvents[1].workerId).toBe('backend');
    expect(parsedEvents[1].type).toBe('waiting-user');
  });
});

describe('Agent command generation', () => {
  it('prefixes every real agent invocation with B2V disabled', () => {
    for (const agent of ['claude', 'codex', 'gemini', 'opencode', 'agy', 'custom-agent']) {
      const command = agentCommand(agent, agent, '/tmp/prompt.txt', false);
      expect(command.startsWith("bash -lc 'B2V_DISABLED=true ")).toBe(true);
      expect(command).toContain(agent);
    }
  });

  it('uses Codex persistent YOLO mode instead of one-shot exec', () => {
    const command = agentCommand('codex', 'codex', '/tmp/prompt.txt', false);

    expect(command).toContain('codex');
    expect(command).toContain('--yolo');
    expect(command).not.toContain('codex exec');
    expect(command).not.toContain('< <(');
  });

  it('uses Gemini YOLO interactive mode', () => {
    const command = agentCommand('gemini', 'gemini', '/tmp/prompt.txt', false);

    expect(command).toContain('gemini');
    expect(command).toContain('--yolo');
    expect(command).toContain(' -i ');
  });

  it('uses OpenCode prompt mode and an automatic callback fallback', () => {
    const command = agentCommand('opencode', 'opencode', '/tmp/prompt.txt', false);

    expect(command).toContain('opencode');
    expect(command).toContain('--prompt');
    expect(command).not.toContain(' run ');
    expect(command).toContain('completed without explicit callback');
  });

  it('uses Antigravity print mode instead of unsupported run subcommand', () => {
    const command = agentCommand('agy', 'agy', '/tmp/prompt.txt', false);

    expect(command).toContain('agy');
    expect(command).toContain('--print');
    expect(command).toContain('--dangerously-skip-permissions');
    expect(command).not.toContain(' run ');
  });

  it('reconstructs restart worker env with B2V disabled and callback metadata', () => {
    const envPrefix = workerEnvPrefix({ id: 'worker one', agent: 'opencode', role: 'Implementer', workstream: 'ui polish' });

    expect(envPrefix.startsWith('B2V_DISABLED=true ')).toBe(true);
    expect(envPrefix).toContain("GAUD_WORKER_ID='worker one'");
    expect(envPrefix).toContain("GAUD_WORKER_ROLE='Implementer'");
    expect(envPrefix).toContain("GAUD_WORKSTREAM='ui polish'");
    expect(envPrefix).toContain("GAUD_AGENT='opencode'");
  });
});

describe('ask_user dialog rendering', () => {
  const ansiTheme = {
    fg: (_color: string, text: string) => `\x1b[38;2;1;2;3m${text}\x1b[39m`,
  };

  it('keeps every rendered line within the terminal width', () => {
    const width = 40;
    const lines = renderAskUserDialogLines({
      question: 'Release script is ready to run, but it uploads GitHub release assets and the channel changes updater metadata.',
      options: [
        {
          label: 'Nightly draft',
          description: 'Recommended. Run `pnpm release -- --channel nightly` (pre-release, updates latest-nightly.json). Safer because it does not move stable users.',
        },
        {
          label: 'Stable draft',
          description: 'Run `pnpm release -- --channel stable` (production updater latest.json). Use this only if the release is intended for all stable users now.',
        },
        {
          label: 'Other — type my own answer',
          description: 'Custom answer',
        },
      ],
      optionIndex: 0,
      editMode: false,
      width,
      theme: ansiTheme,
    });

    expect(lines.length).toBeGreaterThan(0);
    for (const line of lines) {
      expect(visibleWidth(line)).toBeLessThanOrEqual(width);
    }
  });

  it('also truncates embedded editor lines', () => {
    const width = 32;
    const lines = renderAskUserDialogLines({
      question: 'Custom response?',
      options: [{ label: 'Other — type my own answer', description: 'Custom answer' }],
      optionIndex: 0,
      editMode: true,
      editorLines: ['this custom answer is much longer than the dialog can display safely'],
      width,
      theme: ansiTheme,
    });

    for (const line of lines) {
      expect(visibleWidth(line)).toBeLessThanOrEqual(width);
    }
  });
});

describe('Gaud extension widget rendering', () => {
  it('clears the bottom widget for terminal run states', () => {
    const widgetLines = ['GAUD gaud-123 · done'];

    for (const status of ['done', 'failed', 'stopped', 'detached']) {
      expect(gaudWidgetForUi(status, false, widgetLines)).toBeUndefined();
    }
  });

  it('renders the bottom widget only for active runs when the dashboard is closed', () => {
    const widgetLines = ['GAUD gaud-123 · running'];

    expect(gaudWidgetForUi('running', false, widgetLines)).toBe(widgetLines);
    expect(gaudWidgetForUi('running', true, widgetLines)).toBeUndefined();
    expect(gaudWidgetForUi(undefined, false, widgetLines)).toBeUndefined();
  });
});

describe('Gaud routing analysis', () => {
  it('does not prompt for a short single-agent task with an action verb', () => {
    const decision = analyzeGaudRouting('fix the ask_user copy and update the test name');

    expect(decision.shouldPrompt).toBe(false);
    expect(decision.blockers).toContain('single-agent sized by score');
  });

  it('does not use request length alone as a launch signal', () => {
    const decision = analyzeGaudRouting('fix the line width bug in the ask_user dialog by truncating the option descriptions so this one straightforward UI task no longer crashes the terminal renderer');

    expect(decision.shouldPrompt).toBe(false);
    expect(decision.signals).toContain('long detailed request (+1, weak signal)');
  });

  it('prompts for cross-module product work', () => {
    const decision = analyzeGaudRouting('build a dashboard feature with frontend, backend, api, auth, payments, and deployment polish');

    expect(decision.shouldPrompt).toBe(true);
    expect(decision.score).toBeGreaterThanOrEqual(decision.threshold);
  });

  it('does not prompt for informational questions', () => {
    const decision = analyzeGaudRouting('why is Gaud asking to launch the wizard here?');

    expect(decision.shouldPrompt).toBe(false);
    expect(decision.blockers).toContain('informational question');
  });
});

describe('Worker plan generation', () => {
  it('auto-generates role guidance without template worker tickets', () => {
    const plan = createAutogeneratedPlan('reduce gaud planning questions', '/tmp/gaud');

    expect(plan.focus).toContain('reduce gaud planning questions');
    expect(plan.markdown).toContain('## PRD');
    expect(plan.markdown).toContain('## Milestone 1');
    expect(plan.markdown).toContain('## Available Role Catalog');
    expect(plan.markdown).toContain('Configured agents are a pool');
    expect(plan.markdown).toContain('must replace this note with concrete current-milestone tickets');
    expect(plan.markdown).not.toContain('## Ticket 1: Discovery and plan tightening');
    expect(plan.markdown).not.toContain('## Ticket 3: Implementation');
    expect(plan.markdown).toContain('ask the user only for material clarification');
    expect(plan.markdown).toContain('runs at the very end of the milestone after parallel workers finish, to merge/integrate all changes');
    expect(plan.markdown).toContain('Must be strictly isolated from other parallel tickets to avoid conflicts');
  });

  it('delegates worker planning to the foreground agent instead of extension templates', () => {
    const prompt = buildGaudDelegationPrompt('PLAN.md');

    expect(prompt).toContain('foreground Gaud orchestrator');
    expect(prompt).toContain('current-milestone tickets/workstreams');
    expect(prompt).toContain('Use the available role catalog as guidance, not as a launch checklist');
    expect(prompt).toContain('Do not ask the user to manually add workers');
    expect(prompt).toContain('The Pi extension will show the computed assignment');
    expect(prompt).toContain('Do not call gaud_start_run without workers');
    expect(prompt).toContain('strictly distinct, non-overlapping file scopes and objectives');
    expect(prompt).toContain('determine and allocate explicit agents');
    expect(prompt).toContain('sequence a separate integration and review worker');
  });

  it('formats worker assignments for the launch approval gate', () => {
    const summary = formatWorkerApprovalSummary([
      {
        id: 'implementer-1',
        agent: 'opencode',
        role: 'Implementer',
        objective: 'Fix the status cleanup bug after workers complete.',
        files: ['extensions/gaud/index.ts', 'test/state.test.ts'],
        doneCriteria: ['Completed runs no longer stay active.'],
      },
    ], '.gaud/plans/gaud-123-plan.md');

    expect(summary).toContain('Plan: .gaud/plans/gaud-123-plan.md');
    expect(summary).toContain('implementer-1: Implementer via opencode');
    expect(summary).toContain('extensions/gaud/index.ts');
    expect(summary).toContain('Completed runs no longer stay active.');
  });

  it('falls back to one implementer when a plan has no parallel tickets', () => {
    const plans = buildWorkerPlans('Design and code review methodology context', 'review the UX and implement the fix', {
      'gaud-design': 'gemini',
      'gaud-eng': 'claude',
      'gaud-implementer': ['opencode', 'codex'],
      'gaud-code-review': 'claude',
    });

    expect(plans.map((plan) => `${plan.role}/${plan.agent}`)).toEqual(['Implementer/opencode']);
  });

  it('does not dispatch role-catalog entries as workers', () => {
    const generated = createAutogeneratedPlan('fix the extension status cleanup', '/tmp/gaud');
    const plans = buildWorkerPlans(generated.markdown, generated.focus, {
      'gaud-design': 'gemini',
      'gaud-eng': 'claude',
      'gaud-implementer': ['opencode', 'codex'],
      'gaud-code-review': 'claude',
    });

    expect(plans.map((plan) => `${plan.role}/${plan.agent}`)).toEqual(['Implementer/opencode']);
  });

  it('derives workers from ready current-milestone plan tickets', () => {
    const planText = `# Plan

## Milestone 1: Build API and UI

### Tickets

#### Ticket 1: API endpoint
- Owner: Implementer
- Deliverable: Add the API endpoint.
- Files: src/api.ts, test/api.test.ts
- Verification: API tests pass.
- Depends on: none

#### Ticket 2: UI copy
- Owner: UX/UI
- Deliverable: Review and update user-facing copy.
- Files: src/page.tsx
- Verification: UI copy reviewed.
- Depends on: none

#### Ticket 3: Final review
- Owner: Integrator
- Deliverable: Review combined changes after implementation.
- Verification: Final check passes.
- Depends on: Ticket 1

## Future Milestones
`;
    const plans = buildWorkerPlans(planText, 'Build API and UI', {
      'gaud-design': 'gemini',
      'gaud-eng': 'claude',
      'gaud-implementer': ['opencode', 'codex'],
      'gaud-code-review': 'claude',
    });

    expect(plans.map((plan) => `${plan.role}/${plan.agent}`)).toEqual(['Implementer/opencode', 'UX/UI/gemini']);
    expect(plans[0]?.files).toEqual(['src/api.ts', 'test/api.test.ts']);
    expect(plans[0]?.doneCriteria[0]).toContain('API tests pass');
  });
});

describe('Markdown plan discovery', () => {
  it('discovers root markdown plan files before asking for a new idea', async () => {
    const cwd = await mkdtemp(path.join(os.tmpdir(), 'gaud-plan-discovery-'));
    try {
      await writeFile(path.join(cwd, 'README.md'), '# Docs\n', 'utf8');
      await writeFile(path.join(cwd, 'google-drive-firmware-plan.md'), '# Google Drive Firmware Plan\n', 'utf8');

      await expect(discoverDefaultPlanPath(cwd)).resolves.toBe('google-drive-firmware-plan.md');
    } finally {
      await rm(cwd, { recursive: true, force: true });
    }
  });

  it('prefers PLAN.md over generated .gaud plans when both exist', async () => {
    const cwd = await mkdtemp(path.join(os.tmpdir(), 'gaud-plan-priority-'));
    try {
      await mkdir(path.join(cwd, '.gaud', 'plans'), { recursive: true });
      await writeFile(path.join(cwd, '.gaud', 'plans', 'gaud-20260604T213949-plan.md'), '# Previous Plan\n', 'utf8');
      await writeFile(path.join(cwd, 'PLAN.md'), '# Primary Plan\n', 'utf8');

      await expect(discoverDefaultPlanPath(cwd)).resolves.toBe('PLAN.md');
    } finally {
      await rm(cwd, { recursive: true, force: true });
    }
  });

  it('falls back to the newest previous .gaud plan when no root plan exists', async () => {
    const cwd = await mkdtemp(path.join(os.tmpdir(), 'gaud-plan-history-'));
    try {
      const planDir = path.join(cwd, '.gaud', 'plans');
      const olderPath = path.join(planDir, 'gaud-20260604T213048-plan.md');
      const newerPath = path.join(planDir, 'gaud-20260604T213949-plan.md');
      await mkdir(planDir, { recursive: true });
      await writeFile(olderPath, '# Older Plan\n', 'utf8');
      await writeFile(newerPath, '# Newer Plan\n', 'utf8');
      await utimes(olderPath, new Date('2026-06-04T21:30:48Z'), new Date('2026-06-04T21:30:48Z'));
      await utimes(newerPath, new Date('2026-06-04T21:39:49Z'), new Date('2026-06-04T21:39:49Z'));

      await expect(discoverDefaultPlanPath(cwd)).resolves.toBe(path.join('.gaud', 'plans', 'gaud-20260604T213949-plan.md'));
    } finally {
      await rm(cwd, { recursive: true, force: true });
    }
  });

  it('does not fall back to another discovered plan when an explicit markdown path is missing', async () => {
    const cwd = await mkdtemp(path.join(os.tmpdir(), 'gaud-plan-missing-explicit-'));
    try {
      await writeFile(path.join(cwd, 'PLAN.md'), '# Existing Plan\n', 'utf8');

      const source = await resolvePlanningSource(cwd, 'missing-plan.md');

      expect(source.missingExplicitPath).toBe(true);
      expect(source.sourcePath).toBe('missing-plan.md');
      expect(source.absoluteSourcePath).toBe(path.join(cwd, 'missing-plan.md'));
    } finally {
      await rm(cwd, { recursive: true, force: true });
    }
  });
});

describe('Active Run Discovery', () => {
  it('should find the latest active run from the .gaud/runs directory by createdAt', async () => {
    const cwd = await mkdtemp(path.join(os.tmpdir(), 'gaud-active-run-'));
    try {
      const runsDir = path.join(cwd, '.gaud', 'runs');
      await mkdir(runsDir, { recursive: true });

      // Lexically newer, but terminal. Must be ignored.
      const doneDir = path.join(runsDir, 'gaud-20260608T140000');
      await mkdir(doneDir, { recursive: true });
      await writeFile(
        path.join(doneDir, 'state.json'),
        JSON.stringify({
          id: 'gaud-20260608T140000',
          status: 'done',
          task: 'done task',
          createdAt: 3,
          updatedAt: 3,
          repoRoot: cwd,
          runDir: doneDir,
          eventsPath: path.join(doneDir, 'events.jsonl'),
          statePath: path.join(doneDir, 'state.json'),
          tmuxSocket: 'gaud-20260608T140000',
          tmuxSession: 'gaud-20260608T140000',
          workers: {},
          lastEventOffset: 0,
        }),
        'utf8'
      );

      // Lexically older, but most recently created active run. Must win.
      const runningDir = path.join(runsDir, 'gaud-20260608T120000');
      await mkdir(runningDir, { recursive: true });
      await writeFile(
        path.join(runningDir, 'state.json'),
        JSON.stringify({
          id: 'gaud-20260608T120000',
          status: 'running',
          task: 'running task',
          createdAt: 2,
          updatedAt: 2,
          repoRoot: cwd,
          runDir: runningDir,
          eventsPath: path.join(runningDir, 'events.jsonl'),
          statePath: path.join(runningDir, 'state.json'),
          tmuxSocket: 'gaud-20260608T120000',
          tmuxSession: 'gaud-20260608T120000',
          workers: {},
          lastEventOffset: 0,
        }),
        'utf8'
      );

      const olderActiveDir = path.join(runsDir, 'gaud-20260608T130000');
      await mkdir(olderActiveDir, { recursive: true });
      await writeFile(
        path.join(olderActiveDir, 'state.json'),
        JSON.stringify({
          id: 'gaud-20260608T130000',
          status: 'starting',
          task: 'older active task',
          createdAt: 1,
          updatedAt: 1,
          repoRoot: cwd,
          runDir: olderActiveDir,
          eventsPath: path.join(olderActiveDir, 'events.jsonl'),
          statePath: path.join(olderActiveDir, 'state.json'),
          tmuxSocket: 'gaud-20260608T130000',
          tmuxSession: 'gaud-20260608T130000',
          workers: {},
          lastEventOffset: 0,
        }),
        'utf8'
      );

      const active = await findLatestActiveRun(cwd);
      expect(active).toBeDefined();
      expect(active?.id).toBe('gaud-20260608T120000');
      expect(active?.status).toBe('running');
    } finally {
      await rm(cwd, { recursive: true, force: true });
    }
  });

  it('should return undefined if there are no active runs', async () => {
    const cwd = await mkdtemp(path.join(os.tmpdir(), 'gaud-no-active-run-'));
    try {
      const runsDir = path.join(cwd, '.gaud', 'runs');
      await mkdir(runsDir, { recursive: true });

      const run1Dir = path.join(runsDir, 'gaud-20260608T120000');
      await mkdir(run1Dir, { recursive: true });
      await writeFile(
        path.join(run1Dir, 'state.json'),
        JSON.stringify({
          id: 'gaud-20260608T120000',
          status: 'done',
          task: 'task 1',
          createdAt: Date.now(),
          updatedAt: Date.now(),
          repoRoot: cwd,
          runDir: run1Dir,
          eventsPath: path.join(run1Dir, 'events.jsonl'),
          statePath: path.join(run1Dir, 'state.json'),
          tmuxSocket: 'gaud-20260608T120000',
          tmuxSession: 'gaud-20260608T120000',
          workers: {},
          lastEventOffset: 0,
        }),
        'utf8'
      );

      const active = await findLatestActiveRun(cwd);
      expect(active).toBeUndefined();
    } finally {
      await rm(cwd, { recursive: true, force: true });
    }
  });
});

describe('extractPlanPath', () => {
  it('should extract the plan path from task description', () => {
    const task = `Some description\n\nExecution plan: /path/to/my-plan.md`;
    expect(extractPlanPath(task)).toBe('/path/to/my-plan.md');
  });

  it('should ignore status/trailing output details and select the active/existing plan path', () => {
    const task = `M1 — Plan, implement, verify: some task\nExecution plan: /non-existent-plan.md ✓ worker done\n\nExecution plan: /path/to/my-plan.md`;
    expect(extractPlanPath(task)).toBe('/path/to/my-plan.md');
  });

  it('should prioritize the existing plan path over non-existing ones', async () => {
    const tempDir = await mkdtemp(path.join(os.tmpdir(), 'gaud-test-'));
    try {
      const existingPlan = path.join(tempDir, 'existing-plan.md');
      await writeFile(existingPlan, 'plan content');
      
      const task = `M1 — Plan\nExecution plan: /non-existent-path.md ✓ worker done\n\nExecution plan: ${existingPlan}`;
      expect(extractPlanPath(task)).toBe(existingPlan);
    } finally {
      await rm(tempDir, { recursive: true, force: true });
    }
  });
});

