import { describe, it, expect } from 'vitest';
import { agentCommand, buildWorkerPlans, createAutogeneratedPlan, workerEnvPrefix } from '../extensions/gaud/index.js';
import type { GaudRunState } from '../extensions/gaud/index.js';

describe('State Serialization', () => {
  it('should serialize and deserialize a GaudRunState object correctly', () => {
    const run: GaudRunState = {
      id: 'gaud-123',
      status: 'running',
      task: 'implement feature',
      createdAt: Date.now(),
      updatedAt: Date.now(),
      repoRoot: '/root',
      runDir: '/root/.gaud/runs/gaud-123',
      eventsPath: '/root/.gaud/runs/gaud-123/events.jsonl',
      statePath: '/root/.gaud/runs/gaud-123/state.json',
      tmuxSocket: 'gaud-123',
      tmuxSession: 'gaud-123',
      workers: {},
      lastEventOffset: 0,
    };

    const json = JSON.stringify(run);
    const deserialized = JSON.parse(json) as GaudRunState;

    expect(deserialized.id).toBe(run.id);
    expect(deserialized.status).toBe(run.status);
    expect(deserialized.task).toBe(run.task);
  });
});

describe('Polling Bridge - Event Parsing', () => {
  it('should parse valid callback events from a JSONL string', () => {
    const eventsJsonl = [
      JSON.stringify({ ts: Date.now(), runId: 'gaud-123', workerId: 'frontend', type: 'done', summary: 'Implemented UI' }),
      JSON.stringify({ ts: Date.now(), runId: 'gaud-123', workerId: 'backend', type: 'waiting-user', question: 'Confirm API' }),
    ].join('\n');

    const lines = eventsJsonl.split('\n');
    const parsedEvents = lines.map(line => JSON.parse(line));

    expect(parsedEvents).toHaveLength(2);
    expect(parsedEvents[0].workerId).toBe('frontend');
    expect(parsedEvents[0].type).toBe('done');
    expect(parsedEvents[1].workerId).toBe('backend');
    expect(parsedEvents[1].type).toBe('waiting-user');
  });
});

describe('Agent command generation', () => {
  it('uses Codex persistent YOLO mode instead of one-shot exec', () => {
    const command = agentCommand('codex', 'codex', '/tmp/prompt.txt', false);

    expect(command).toContain('codex');
    expect(command).toContain('--yolo');
    expect(command).not.toContain('codex exec');
    expect(command).not.toContain('< <(');
  });

  it('uses Gemini YOLO interactive mode', () => {
    const command = agentCommand('gemini', 'gemini', '/tmp/prompt.txt', false);

    expect(command).toContain('gemini');
    expect(command).toContain('--yolo');
    expect(command).toContain(' -i ');
  });

  it('uses OpenCode prompt mode and an automatic callback fallback', () => {
    const command = agentCommand('opencode', 'opencode', '/tmp/prompt.txt', false);

    expect(command).toContain('opencode');
    expect(command).toContain('--prompt');
    expect(command).not.toContain(' run ');
    expect(command).toContain('completed without explicit callback');
  });

  it('uses Antigravity print mode instead of unsupported run subcommand', () => {
    const command = agentCommand('agy', 'agy', '/tmp/prompt.txt', false);

    expect(command).toContain('agy');
    expect(command).toContain('--print');
    expect(command).toContain('--dangerously-skip-permissions');
    expect(command).not.toContain(' run ');
  });

  it('reconstructs restart worker env with B2V disabled and callback metadata', () => {
    const envPrefix = workerEnvPrefix({ id: 'worker one', agent: 'opencode', role: 'Implementer', workstream: 'ui polish' });

    expect(envPrefix).toContain('B2V_DISABLED=true');
    expect(envPrefix).toContain("GAUD_WORKER_ID='worker one'");
    expect(envPrefix).toContain("GAUD_WORKER_ROLE='Implementer'");
    expect(envPrefix).toContain("GAUD_WORKSTREAM='ui polish'");
    expect(envPrefix).toContain("GAUD_AGENT='opencode'");
  });
});

describe('Worker plan generation', () => {
  it('auto-generates a full milestone plan from one request without interview answers', () => {
    const plan = createAutogeneratedPlan('reduce gaud planning questions', '/tmp/gaud');

    expect(plan.focus).toContain('reduce gaud planning questions');
    expect(plan.markdown).toContain('## PRD');
    expect(plan.markdown).toContain('## Milestone 1');
    expect(plan.markdown).toContain('## Ticket 3: Implementation');
    expect(plan.markdown).toContain('ask the user only for material clarification');
  });

  it('keeps implementer assignments as implementers when plan text mentions review', () => {
    const plans = buildWorkerPlans('Design and code review methodology context', 'review the UX and implement the fix', {
      'gaud-design': 'gemini',
      'gaud-eng': 'claude',
      'gaud-implementer': ['opencode'],
      'gaud-code-review': 'claude',
    });

    expect(plans.map((plan) => plan.role)).toEqual([
      'TPM',
      'Investigator',
      'UX/UI',
      'Implementer',
      'Integrator',
    ]);
    expect(plans[3]?.id).toBe('implementer-4');
  });
});
