import { describe, it, expect } from 'vitest';
import { mkdir, mkdtemp, rm, utimes, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { visibleWidth } from '@earendil-works/pi-tui';
import { agentCommand, buildWorkerPlans, createAutogeneratedPlan, discoverDefaultPlanPath, renderAskUserDialogLines, resolvePlanningSource, workerEnvPrefix } from '../extensions/gaud/index.js';
import type { GaudRunState } from '../extensions/gaud/index.js';

describe('State Serialization', () => {
  it('should serialize and deserialize a GaudRunState object correctly', () => {
    const run: GaudRunState = {
      id: 'gaud-123',
      status: 'running',
      task: 'implement feature',
      createdAt: Date.now(),
      updatedAt: Date.now(),
      repoRoot: '/root',
      runDir: '/root/.gaud/runs/gaud-123',
      eventsPath: '/root/.gaud/runs/gaud-123/events.jsonl',
      statePath: '/root/.gaud/runs/gaud-123/state.json',
      tmuxSocket: 'gaud-123',
      tmuxSession: 'gaud-123',
      workers: {},
      lastEventOffset: 0,
    };

    const json = JSON.stringify(run);
    const deserialized = JSON.parse(json) as GaudRunState;

    expect(deserialized.id).toBe(run.id);
    expect(deserialized.status).toBe(run.status);
    expect(deserialized.task).toBe(run.task);
  });
});

describe('Polling Bridge - Event Parsing', () => {
  it('should parse valid callback events from a JSONL string', () => {
    const eventsJsonl = [
      JSON.stringify({ ts: Date.now(), runId: 'gaud-123', workerId: 'frontend', type: 'done', summary: 'Implemented UI' }),
      JSON.stringify({ ts: Date.now(), runId: 'gaud-123', workerId: 'backend', type: 'waiting-user', question: 'Confirm API' }),
    ].join('\n');

    const lines = eventsJsonl.split('\n');
    const parsedEvents = lines.map(line => JSON.parse(line));

    expect(parsedEvents).toHaveLength(2);
    expect(parsedEvents[0].workerId).toBe('frontend');
    expect(parsedEvents[0].type).toBe('done');
    expect(parsedEvents[1].workerId).toBe('backend');
    expect(parsedEvents[1].type).toBe('waiting-user');
  });
});

describe('Agent command generation', () => {
  it('uses Codex persistent YOLO mode instead of one-shot exec', () => {
    const command = agentCommand('codex', 'codex', '/tmp/prompt.txt', false);

    expect(command).toContain('codex');
    expect(command).toContain('--yolo');
    expect(command).not.toContain('codex exec');
    expect(command).not.toContain('< <(');
  });

  it('uses Gemini YOLO interactive mode', () => {
    const command = agentCommand('gemini', 'gemini', '/tmp/prompt.txt', false);

    expect(command).toContain('gemini');
    expect(command).toContain('--yolo');
    expect(command).toContain(' -i ');
  });

  it('uses OpenCode prompt mode and an automatic callback fallback', () => {
    const command = agentCommand('opencode', 'opencode', '/tmp/prompt.txt', false);

    expect(command).toContain('opencode');
    expect(command).toContain('--prompt');
    expect(command).not.toContain(' run ');
    expect(command).toContain('completed without explicit callback');
  });

  it('uses Antigravity print mode instead of unsupported run subcommand', () => {
    const command = agentCommand('agy', 'agy', '/tmp/prompt.txt', false);

    expect(command).toContain('agy');
    expect(command).toContain('--print');
    expect(command).toContain('--dangerously-skip-permissions');
    expect(command).not.toContain(' run ');
  });

  it('reconstructs restart worker env with B2V disabled and callback metadata', () => {
    const envPrefix = workerEnvPrefix({ id: 'worker one', agent: 'opencode', role: 'Implementer', workstream: 'ui polish' });

    expect(envPrefix).toContain('B2V_DISABLED=true');
    expect(envPrefix).toContain("GAUD_WORKER_ID='worker one'");
    expect(envPrefix).toContain("GAUD_WORKER_ROLE='Implementer'");
    expect(envPrefix).toContain("GAUD_WORKSTREAM='ui polish'");
    expect(envPrefix).toContain("GAUD_AGENT='opencode'");
  });
});

describe('ask_user dialog rendering', () => {
  const ansiTheme = {
    fg: (_color: string, text: string) => `\x1b[38;2;1;2;3m${text}\x1b[39m`,
  };

  it('keeps every rendered line within the terminal width', () => {
    const width = 40;
    const lines = renderAskUserDialogLines({
      question: 'Release script is ready to run, but it uploads GitHub release assets and the channel changes updater metadata.',
      options: [
        {
          label: 'Nightly draft',
          description: 'Recommended. Run `pnpm release -- --channel nightly` (pre-release, updates latest-nightly.json). Safer because it does not move stable users.',
        },
        {
          label: 'Stable draft',
          description: 'Run `pnpm release -- --channel stable` (production updater latest.json). Use this only if the release is intended for all stable users now.',
        },
        {
          label: 'Other — type my own answer',
          description: 'Custom answer',
        },
      ],
      optionIndex: 0,
      editMode: false,
      width,
      theme: ansiTheme,
    });

    expect(lines.length).toBeGreaterThan(0);
    for (const line of lines) {
      expect(visibleWidth(line)).toBeLessThanOrEqual(width);
    }
  });

  it('also truncates embedded editor lines', () => {
    const width = 32;
    const lines = renderAskUserDialogLines({
      question: 'Custom response?',
      options: [{ label: 'Other — type my own answer', description: 'Custom answer' }],
      optionIndex: 0,
      editMode: true,
      editorLines: ['this custom answer is much longer than the dialog can display safely'],
      width,
      theme: ansiTheme,
    });

    for (const line of lines) {
      expect(visibleWidth(line)).toBeLessThanOrEqual(width);
    }
  });
});

describe('Worker plan generation', () => {
  it('auto-generates a full milestone plan from one request without interview answers', () => {
    const plan = createAutogeneratedPlan('reduce gaud planning questions', '/tmp/gaud');

    expect(plan.focus).toContain('reduce gaud planning questions');
    expect(plan.markdown).toContain('## PRD');
    expect(plan.markdown).toContain('## Milestone 1');
    expect(plan.markdown).toContain('## Ticket 3: Implementation');
    expect(plan.markdown).toContain('ask the user only for material clarification');
  });

  it('keeps implementer assignments as implementers when plan text mentions review', () => {
    const plans = buildWorkerPlans('Design and code review methodology context', 'review the UX and implement the fix', {
      'gaud-design': 'gemini',
      'gaud-eng': 'claude',
      'gaud-implementer': ['opencode'],
      'gaud-code-review': 'claude',
    });

    expect(plans.map((plan) => plan.role)).toEqual([
      'TPM',
      'Investigator',
      'UX/UI',
      'Implementer',
      'Integrator',
    ]);
    expect(plans[3]?.id).toBe('implementer-4');
  });
});

describe('Markdown plan discovery', () => {
  it('discovers root markdown plan files before asking for a new idea', async () => {
    const cwd = await mkdtemp(path.join(os.tmpdir(), 'gaud-plan-discovery-'));
    try {
      await writeFile(path.join(cwd, 'README.md'), '# Docs\n', 'utf8');
      await writeFile(path.join(cwd, 'google-drive-firmware-plan.md'), '# Google Drive Firmware Plan\n', 'utf8');

      await expect(discoverDefaultPlanPath(cwd)).resolves.toBe('google-drive-firmware-plan.md');
    } finally {
      await rm(cwd, { recursive: true, force: true });
    }
  });

  it('prefers PLAN.md over generated .gaud plans when both exist', async () => {
    const cwd = await mkdtemp(path.join(os.tmpdir(), 'gaud-plan-priority-'));
    try {
      await mkdir(path.join(cwd, '.gaud', 'plans'), { recursive: true });
      await writeFile(path.join(cwd, '.gaud', 'plans', 'gaud-20260604T213949-plan.md'), '# Previous Plan\n', 'utf8');
      await writeFile(path.join(cwd, 'PLAN.md'), '# Primary Plan\n', 'utf8');

      await expect(discoverDefaultPlanPath(cwd)).resolves.toBe('PLAN.md');
    } finally {
      await rm(cwd, { recursive: true, force: true });
    }
  });

  it('falls back to the newest previous .gaud plan when no root plan exists', async () => {
    const cwd = await mkdtemp(path.join(os.tmpdir(), 'gaud-plan-history-'));
    try {
      const planDir = path.join(cwd, '.gaud', 'plans');
      const olderPath = path.join(planDir, 'gaud-20260604T213048-plan.md');
      const newerPath = path.join(planDir, 'gaud-20260604T213949-plan.md');
      await mkdir(planDir, { recursive: true });
      await writeFile(olderPath, '# Older Plan\n', 'utf8');
      await writeFile(newerPath, '# Newer Plan\n', 'utf8');
      await utimes(olderPath, new Date('2026-06-04T21:30:48Z'), new Date('2026-06-04T21:30:48Z'));
      await utimes(newerPath, new Date('2026-06-04T21:39:49Z'), new Date('2026-06-04T21:39:49Z'));

      await expect(discoverDefaultPlanPath(cwd)).resolves.toBe(path.join('.gaud', 'plans', 'gaud-20260604T213949-plan.md'));
    } finally {
      await rm(cwd, { recursive: true, force: true });
    }
  });

  it('does not fall back to another discovered plan when an explicit markdown path is missing', async () => {
    const cwd = await mkdtemp(path.join(os.tmpdir(), 'gaud-plan-missing-explicit-'));
    try {
      await writeFile(path.join(cwd, 'PLAN.md'), '# Existing Plan\n', 'utf8');

      const source = await resolvePlanningSource(cwd, 'missing-plan.md');

      expect(source.missingExplicitPath).toBe(true);
      expect(source.sourcePath).toBe('missing-plan.md');
      expect(source.absoluteSourcePath).toBe(path.join(cwd, 'missing-plan.md'));
    } finally {
      await rm(cwd, { recursive: true, force: true });
    }
  });
});
